apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-git-values-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/htijas/argocd-example-apps'
    path: helm-guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
